apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-network-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: irdanish11/kube-demo-frontend:latest