
Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
 
  config.vm.define "web" do |web|
    web.vm.box = "apache"
    web.vm.network "private_network", ip: "192.168.56.17"
    web.vm.network "public_network"
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = 1
    end
  end
 
  config.vm.define "db" do |db|
    db.vm.box = "mysql"
    db.vm.network "private_network", ip: "192.168.56.18"
    db.vm.network "public_network"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = 1
    end
end