apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-network-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: irdanish11/kube-demo-auth:latest