apiVersion: apps/v1
kind: Deployment
metadata:
  name: story
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story-app
  template:
    metadata:
      labels:
        app: story-app
    spec:
      containers:
        - name: story
          image: irdanish11/kub-data-demo:1
          env: 
            - name: STORY_DIR
              # value: story
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts: 
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim:
            claimName: host-pvc
